package cmd

func registerSubcommands(root *rootCmd) {
	root.AddCommand(newInitCmd())
	root.AddCommand(newSealCmd())
	root.AddCommand(newOpenCmd())
	root.AddCommand(newDiffCmd())
	root.AddCommand(newRotateCmd())
	root.AddCommand(newKeysCmd())
	root.AddCommand(newVersionCmd())
	root.AddCommand(newEditCmd())
	root.AddCommand(newExportCmd())
	root.AddCommand(newListCmd())
	root.AddCommand(newStatusCmd())
	root.AddCommand(newCopyCmd())
	root.AddCommand(newRenameCmd())
	root.AddCommand(newRekeyCmd())
	root.AddCommand(newImportCmd())
	root.AddCommand(newMergeCmd())
	root.AddCommand(newLintCmd())
	root.AddCommand(newSnapshotCmd())
	root.AddCommand(newAuditCmd())
	root.AddCommand(newSchemaCmd())
	root.AddCommand(newTransformCmd())
	root.AddCommand(newEnvCmd())
	root.AddCommand(newPromoteCmd())
	root.AddCommand(newFilterCmd())
	root.AddCommand(newRenameKeyCmd())
	root.AddCommand(newCloneCmd())
	root.AddCommand(newSummarizeCmd())
	root.AddCommand(newNormalizeCmd())
	root.AddCommand(newCompareCmd())
	root.AddCommand(newTagsCmd())
}
